LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

# ./configure --build=x86_64-pc-linux-gnu --host=arm-linux-eabi
# find proj-4.9.3 -name "*.c" | grep -Ev "tests|doc" | sort | awk '{ print "\t"$1" \\" }'

LOCAL_MODULE := proj4

LOCAL_SRC_FILES := \
    $(PROJ4_PATH)/src/aasincos.c \
    $(PROJ4_PATH)/src/adjlon.c \
    $(PROJ4_PATH)/src/bch2bps.c \
    $(PROJ4_PATH)/src/bchgen.c \
    $(PROJ4_PATH)/src/biveval.c \
    $(PROJ4_PATH)/src/cs2cs.c \
    $(PROJ4_PATH)/src/dmstor.c \
    $(PROJ4_PATH)/src/emess.c \
    $(PROJ4_PATH)/src/gen_cheb.c \
    $(PROJ4_PATH)/src/geocent.c \
    $(PROJ4_PATH)/src/geod.c \
    $(PROJ4_PATH)/src/geodesic.c \
    $(PROJ4_PATH)/src/geod_interface.c \
    $(PROJ4_PATH)/src/geod_set.c \
    $(PROJ4_PATH)/src/geodtest.c \
    $(PROJ4_PATH)/src/jniproj.c \
    $(PROJ4_PATH)/src/mk_cheby.c \
    $(PROJ4_PATH)/src/multistresstest.c \
    $(PROJ4_PATH)/src/nad2bin.c \
    $(PROJ4_PATH)/src/nad_cvt.c \
    $(PROJ4_PATH)/src/nad_init.c \
    $(PROJ4_PATH)/src/nad_intr.c \
    $(PROJ4_PATH)/src/PJ_aea.c \
    $(PROJ4_PATH)/src/PJ_aeqd.c \
    $(PROJ4_PATH)/src/PJ_airy.c \
    $(PROJ4_PATH)/src/PJ_aitoff.c \
    $(PROJ4_PATH)/src/pj_apply_gridshift.c \
    $(PROJ4_PATH)/src/pj_apply_vgridshift.c \
    $(PROJ4_PATH)/src/PJ_august.c \
    $(PROJ4_PATH)/src/pj_auth.c \
    $(PROJ4_PATH)/src/PJ_bacon.c \
    $(PROJ4_PATH)/src/PJ_bipc.c \
    $(PROJ4_PATH)/src/PJ_boggs.c \
    $(PROJ4_PATH)/src/PJ_bonne.c \
    $(PROJ4_PATH)/src/PJ_calcofi.c \
    $(PROJ4_PATH)/src/PJ_cass.c \
    $(PROJ4_PATH)/src/PJ_cc.c \
    $(PROJ4_PATH)/src/PJ_cea.c \
    $(PROJ4_PATH)/src/PJ_chamb.c \
    $(PROJ4_PATH)/src/PJ_collg.c \
    $(PROJ4_PATH)/src/PJ_comill.c \
    $(PROJ4_PATH)/src/PJ_crast.c \
    $(PROJ4_PATH)/src/pj_ctx.c \
    $(PROJ4_PATH)/src/pj_datums.c \
    $(PROJ4_PATH)/src/pj_datum_set.c \
    $(PROJ4_PATH)/src/PJ_denoy.c \
    $(PROJ4_PATH)/src/pj_deriv.c \
    $(PROJ4_PATH)/src/PJ_eck1.c \
    $(PROJ4_PATH)/src/PJ_eck2.c \
    $(PROJ4_PATH)/src/PJ_eck3.c \
    $(PROJ4_PATH)/src/PJ_eck4.c \
    $(PROJ4_PATH)/src/PJ_eck5.c \
    $(PROJ4_PATH)/src/pj_ellps.c \
    $(PROJ4_PATH)/src/pj_ell_set.c \
    $(PROJ4_PATH)/src/PJ_eqc.c \
    $(PROJ4_PATH)/src/PJ_eqdc.c \
    $(PROJ4_PATH)/src/pj_errno.c \
    $(PROJ4_PATH)/src/pj_factors.c \
    $(PROJ4_PATH)/src/PJ_fahey.c \
    $(PROJ4_PATH)/src/pj_fileapi.c \
    $(PROJ4_PATH)/src/PJ_fouc_s.c \
    $(PROJ4_PATH)/src/pj_fwd.c \
    $(PROJ4_PATH)/src/pj_fwd3d.c \
    $(PROJ4_PATH)/src/PJ_gall.c \
    $(PROJ4_PATH)/src/pj_gauss.c \
    $(PROJ4_PATH)/src/pj_gc_reader.c \
    $(PROJ4_PATH)/src/pj_generic_selftest.c \
    $(PROJ4_PATH)/src/pj_geocent.c \
    $(PROJ4_PATH)/src/PJ_geos.c \
    $(PROJ4_PATH)/src/PJ_gins8.c \
    $(PROJ4_PATH)/src/PJ_gnom.c \
    $(PROJ4_PATH)/src/PJ_gn_sinu.c \
    $(PROJ4_PATH)/src/PJ_goode.c \
    $(PROJ4_PATH)/src/pj_gridcatalog.c \
    $(PROJ4_PATH)/src/pj_gridinfo.c \
    $(PROJ4_PATH)/src/pj_gridlist.c \
    $(PROJ4_PATH)/src/PJ_gstmerc.c \
    $(PROJ4_PATH)/src/PJ_hammer.c \
    $(PROJ4_PATH)/src/PJ_hatano.c \
    $(PROJ4_PATH)/src/PJ_healpix.c \
    $(PROJ4_PATH)/src/PJ_igh.c \
    $(PROJ4_PATH)/src/PJ_imw_p.c \
    $(PROJ4_PATH)/src/pj_init.c \
    $(PROJ4_PATH)/src/pj_initcache.c \
    $(PROJ4_PATH)/src/pj_inv.c \
    $(PROJ4_PATH)/src/pj_inv3d.c \
    $(PROJ4_PATH)/src/PJ_isea.c \
    $(PROJ4_PATH)/src/PJ_krovak.c \
    $(PROJ4_PATH)/src/PJ_labrd.c \
    $(PROJ4_PATH)/src/PJ_laea.c \
    $(PROJ4_PATH)/src/PJ_lagrng.c \
    $(PROJ4_PATH)/src/PJ_larr.c \
    $(PROJ4_PATH)/src/PJ_lask.c \
    $(PROJ4_PATH)/src/pj_latlong.c \
    $(PROJ4_PATH)/src/PJ_lcc.c \
    $(PROJ4_PATH)/src/PJ_lcca.c \
    $(PROJ4_PATH)/src/pj_list.c \
    $(PROJ4_PATH)/src/pj_log.c \
    $(PROJ4_PATH)/src/PJ_loxim.c \
    $(PROJ4_PATH)/src/PJ_lsat.c \
    $(PROJ4_PATH)/src/pj_malloc.c \
    $(PROJ4_PATH)/src/PJ_mbtfpp.c \
    $(PROJ4_PATH)/src/PJ_mbtfpq.c \
    $(PROJ4_PATH)/src/PJ_mbt_fps.c \
    $(PROJ4_PATH)/src/PJ_merc.c \
    $(PROJ4_PATH)/src/PJ_mill.c \
    $(PROJ4_PATH)/src/PJ_misrsom.c \
    $(PROJ4_PATH)/src/pj_mlfn.c \
    $(PROJ4_PATH)/src/PJ_mod_ster.c \
    $(PROJ4_PATH)/src/PJ_moll.c \
    $(PROJ4_PATH)/src/pj_msfn.c \
    $(PROJ4_PATH)/src/pj_mutex.c \
    $(PROJ4_PATH)/src/PJ_natearth.c \
    $(PROJ4_PATH)/src/PJ_natearth2.c \
    $(PROJ4_PATH)/src/PJ_nell.c \
    $(PROJ4_PATH)/src/PJ_nell_h.c \
    $(PROJ4_PATH)/src/PJ_nocol.c \
    $(PROJ4_PATH)/src/PJ_nsper.c \
    $(PROJ4_PATH)/src/PJ_nzmg.c \
    $(PROJ4_PATH)/src/PJ_ob_tran.c \
    $(PROJ4_PATH)/src/PJ_ocea.c \
    $(PROJ4_PATH)/src/PJ_oea.c \
    $(PROJ4_PATH)/src/PJ_omerc.c \
    $(PROJ4_PATH)/src/pj_open_lib.c \
    $(PROJ4_PATH)/src/PJ_ortho.c \
    $(PROJ4_PATH)/src/pj_param.c \
    $(PROJ4_PATH)/src/PJ_patterson.c \
    $(PROJ4_PATH)/src/pj_phi2.c \
    $(PROJ4_PATH)/src/PJ_poly.c \
    $(PROJ4_PATH)/src/pj_pr_list.c \
    $(PROJ4_PATH)/src/PJ_putp2.c \
    $(PROJ4_PATH)/src/PJ_putp3.c \
    $(PROJ4_PATH)/src/PJ_putp4p.c \
    $(PROJ4_PATH)/src/PJ_putp5.c \
    $(PROJ4_PATH)/src/PJ_putp6.c \
    $(PROJ4_PATH)/src/PJ_qsc.c \
    $(PROJ4_PATH)/src/pj_qsfn.c \
    $(PROJ4_PATH)/src/pj_release.c \
    $(PROJ4_PATH)/src/PJ_robin.c \
    $(PROJ4_PATH)/src/PJ_rpoly.c \
    $(PROJ4_PATH)/src/pj_run_selftests.c \
    $(PROJ4_PATH)/src/PJ_sch.c \
    $(PROJ4_PATH)/src/PJ_sconics.c \
    $(PROJ4_PATH)/src/PJ_somerc.c \
    $(PROJ4_PATH)/src/PJ_stere.c \
    $(PROJ4_PATH)/src/PJ_sterea.c \
    $(PROJ4_PATH)/src/pj_strerrno.c \
    $(PROJ4_PATH)/src/pj_strtod.c \
    $(PROJ4_PATH)/src/PJ_sts.c \
    $(PROJ4_PATH)/src/PJ_tcc.c \
    $(PROJ4_PATH)/src/PJ_tcea.c \
    $(PROJ4_PATH)/src/PJ_times.c \
    $(PROJ4_PATH)/src/PJ_tmerc.c \
    $(PROJ4_PATH)/src/PJ_tpeqd.c \
    $(PROJ4_PATH)/src/pj_transform.c \
    $(PROJ4_PATH)/src/pj_tsfn.c \
    $(PROJ4_PATH)/src/pj_units.c \
    $(PROJ4_PATH)/src/PJ_urm5.c \
    $(PROJ4_PATH)/src/PJ_urmfps.c \
    $(PROJ4_PATH)/src/pj_utils.c \
    $(PROJ4_PATH)/src/PJ_vandg.c \
    $(PROJ4_PATH)/src/PJ_vandg2.c \
    $(PROJ4_PATH)/src/PJ_vandg4.c \
    $(PROJ4_PATH)/src/PJ_wag2.c \
    $(PROJ4_PATH)/src/PJ_wag3.c \
    $(PROJ4_PATH)/src/PJ_wag7.c \
    $(PROJ4_PATH)/src/PJ_wink1.c \
    $(PROJ4_PATH)/src/PJ_wink2.c \
    $(PROJ4_PATH)/src/pj_zpoly1.c \
    $(PROJ4_PATH)/src/proj.c \
    $(PROJ4_PATH)/src/proj_etmerc.c \
    $(PROJ4_PATH)/src/proj_mdist.c \
    $(PROJ4_PATH)/src/proj_rouss.c \
    $(PROJ4_PATH)/src/p_series.c \
    $(PROJ4_PATH)/src/rtodms.c \
    $(PROJ4_PATH)/src/test228.c \
    $(PROJ4_PATH)/src/vector1.c

LOCAL_C_INCLUDES := $(LOCAL_PATH)/$(PROJ4_PATH)/src

LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/$(PROJ4_PATH)/src \

include $(BUILD_STATIC_LIBRARY)
