/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_proj4_GridInfo_CTable */

#ifndef _Included_org_proj4_GridInfo_CTable
#define _Included_org_proj4_GridInfo_CTable
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
