/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_proj4_GridInfo_Format */

#ifndef _Included_org_proj4_GridInfo_Format
#define _Included_org_proj4_GridInfo_Format
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
